# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=30, verbose_name='国名')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='商品画像')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='名')),
                ('last_name', models.CharField(max_length=30, verbose_name='姓')),
                ('postal_code', models.CharField(max_length=30, verbose_name='郵便番号')),
                ('prefecture', models.CharField(max_length=30, verbose_name='都道府県')),
                ('city', models.CharField(max_length=30, verbose_name='市区町村')),
                ('street1', models.CharField(max_length=30, verbose_name='番地など')),
                ('street2', models.CharField(blank=True, max_length=30, verbose_name='建物名など')),
                ('tel', models.CharField(blank=True, max_length=30, verbose_name='電話番号')),
                ('email', models.CharField(max_length=200, verbose_name='メールアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='注文日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='注文個数')),
                ('price', models.IntegerField(verbose_name='注文時の価格')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='決済名')),
                ('payment_type', models.CharField(max_length=30, verbose_name='決済種別')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商品名')),
                ('description', models.CharField(blank=True, max_length=30, verbose_name='商品説明')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('image', models.FileField(blank=True, upload_to='', verbose_name='商品画像')),
                ('stock', models.IntegerField(verbose_name='在庫数')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='商品の販売状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('cacao', models.IntegerField(default=0, verbose_name='カカオの割合')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Country')),
            ],
        ),
        migrations.AddField(
            model_name='order_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='ecommerce.Order_Product', to='ecommerce.Product'),
        ),
    ]
